# Generated by Django 3.2.8 on 2021-11-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
