# Generated by Django 3.2.8 on 2021-11-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_proficiencybonus_charactersheet_proficiency_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='is_friendly',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='is_npc',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spell',
            name='description',
            field=models.CharField(max_length=4095),
        ),
    ]
