# Generated by Django 3.2.8 on 2021-11-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_spell_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='duration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='spell',
            name='range',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
