# Generated by Django 3.2.8 on 2021-11-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211130_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='extra_damage',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
