# Generated by Django 3.2.8 on 2021-12-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_npcinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='healing',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
