# Generated by Django 3.2.8 on 2021-12-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_spell_healing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='die_count',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='die_sides',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='extra_damage',
        ),
        migrations.AddField(
            model_name='spell',
            name='damage',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='healing',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
